### ISSUE TITLE
If I want to visualize a face recognition model, what should I do? I don't seem to see any examples of this

### ISSUE THREAD

**Issue by SuperCarryFu** [jacobgil/pytorch-grad-cam#218]

**Comment by jacobgil** [comment]
What is the model output?
Is it a feature vector, for example used for computing similarity scores between faces? Or something else?

**Comment by SuperCarryFu** [comment]
Is it a feature vector，Input a face picture, get a feature vector

**Comment by jacobgil** [comment]
We would have to define a custom target for this, instead of the classifier target. 
Something like

```python
class FaceRecognitionTarget:
    def __init__(self, target_face_features):
        self.target_face_features = target_face_features
    def __call__(self, model_output):
         return torch.dot(model_output, self.target_face_features)
```

To see what in the image is similar to a target face, create the target for the target face representation.

Can replace the dot here with L2 norm, cosine similarity, or anything else that is appropriate for computing the similarity between the vectors.

This would be a good example to add as a notebook for this repo.
I can add this, but might take me 1-2 weeks to get to it.

**Comment by SuperCarryFu** [comment]
Thank you very much and I look forward to your updates




---Original---
From: "Jacob ***@***.***&gt;
Date: Thu, Mar 31, 2022 13:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jacobgil/pytorch-grad-cam] If I want to visualize a facerecognition model, what should I do? I don't seem to see any examples of this(Issue #218)




 
We would have to define a custom target for this, instead of the classifier target.
 Something like
 class FaceRecognitionTarget:     def __init__(self, target_face_features):         self.target_face_features = target_face_features     def __call__(self, model_output):          return torch.dot(model_output, self.target_face_features)
 
To see what in the image is similar to a target face, create the target for the target face representation.
 
Can replace the dot here with L2 norm, cosine similarity, or anything else that is appropriate for computing the similarity between the vectors.
 
This would be a good example to add as a notebook for this repo.
 I can add this, but might take me 1-2 weeks to get to it.
