### ISSUE TITLE
object detection not woking properly

### ISSUE THREAD

**Issue by sanjaypavo** [jacobgil/pytorch-grad-cam#227]
Hello, I have tried the fasterrcnn model with some images and it was not producing good results, I have attached the output screenshots, can you please elaborate on the reason for this?
![torch_output](https://user-images.githubusercontent.com/93761297/162442453-014958c9-7718-4b1e-a591-08033dcff820.png)

**Comment by jacobgil** [comment]
If you can post the original image, the model, the target_layer etc (are these like in the notebook),
Ideally some code snippet,
I can try taking a look at it.


Is this EigenCAM or AblationCAM?

**Comment by sanjaypavo** [comment]
> If you can post the original image, the model, the target_layer etc (are these like in the notebook?), Ideally some code snippet, I can try taking a look at it.
> 
> Is this EigenCAM or AblationCAM?

Hi, the model, target layers are exactly the same as in this [notebook](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.ipynb). This result was generated using Eigencam. I am also attaching the original image
![bus](https://user-images.githubusercontent.com/93761297/162673667-a0c5cf4b-6936-4231-99e1-2ec631979184.jpg)
.

**Comment by jacobgil** [comment]
Hi,

The problem seems to be that the activations on the bus are larger than on the other objects, so the bus is shadowing everything else.
One way to deal with this would be to renormalize the CAM of every bounding box.
However in the notebook I just saw I had a small bug in the implementation of the renormalization.
It should be like this:

```python
def renormalize_cam_in_bounding_boxes(boxes, image_float_np, grayscale_cam):
    """Normalize the CAM to be in the range [0, 1] 
    inside every bounding boxes, and zero outside of the bounding boxes. """
    renormalized_cam = np.zeros(grayscale_cam.shape, dtype=np.float32)
    images = []
    for x1, y1, x2, y2 in boxes:
        img = renormalized_cam * 0
        img[y1:y2, x1:x2] = scale_cam_image(grayscale_cam[y1:y2, x1:x2].copy())    
        images.append(img)
    
    renormalized_cam = np.max(np.float32(images), axis = 0)
    renormalized_cam = scale_cam_image(renormalized_cam)
    eigencam_image_renormalized = show_cam_on_image(image_float_np, renormalized_cam, use_rgb=True)
    image_with_bounding_boxes = draw_boxes(boxes, labels, classes, eigencam_image_renormalized)
    return image_with_bounding_boxes
```

I'm going to soon push a fix for this.

In the meanwhile, attached the result I got for your image, which I think is an improvement.
![image](https://user-images.githubusercontent.com/5342073/163681984-24cc1276-acf2-461b-ade3-b7ed7cbda6b6.png)

**Comment by jacobgil** [comment]
Hi, I hope this solved this issue.
Closing this issue for now, please re open if you have questions.
