### ISSUE TITLE
GradCAM - targets 

### ISSUE THREAD

**Issue by kinassatim** [jacobgil/pytorch-grad-cam#280]
Hi, could you help me understand targets in gradCAM (probably I made some mistake or do not understand this)? For targets I used ClassifierOutputTarget provided in utils.py. In my case I have two classes (0/1 stored in row.cls). 

My model predictions looks like below:

   GT (row.cls)    PRED
a. 0                  1   
b. 0                 0   
c. 0                  0   

Firstly I generated gradCAM without targets parameters. 

```
for row in ds:
  cam_destination = GradCAM(model=model, target_layers=target_layer, use_cuda=True)
  output_destination = cam_destination(input_tensor=x_image.unsqueeze(0))
  vis_destination = show_cam_on_image(x_image.numpy().transpose((1, 2, 0)), output_destination[0], use_rgb=True)
```

Then decided to generate gradCAM for ground truth classes.

```
for row in ds:
  cam_destination = GradCAM(model=model, target_layers=target_layer, use_cuda=True)
  output_destination = cam_destination(input_tensor=x_image.unsqueeze(0), targets=[ClassifierOutputTarget(row.cls)])
  vis_destination = show_cam_on_image(x_image.numpy().transpose((1, 2, 0)), output_destination[0], use_rgb=True)
```

What I got? For cases a, b, c ...

a. different gradCAM
b. the same gradCAM
c. different gradCAM

The most interesting answer is for "c" - why I got different gradCAMs if we have the same predicted and baseline class? I suppose that they should be the same. Could you help me understand targets (my mistake)?

**Comment by jacobgil** [comment]
Hi, thanks for posting.

Apparently for c it's supposed to be the same.

First I want to rule out some issues, that could potentially explain a difference in the prediction from the model inside the gradcam object, and "externally" (what you have in the PRED column).

1. Is the model in eval mode and not in debug mode ?
2. Is the input tensor normalization here correct ?
I noticed that show_cam_on_image got the same tensor (after transposing the channels).
Very commonly an image-net normalization is used, so I just want to make sure this is intentional, because it could explain a difference in the PRED column and in what the model gets.

**Comment by kinassatim** [comment]
Hi,
thank you for answer. I checked code - model is in eval state but ... second reason is possible. I will check this and let you know if I solve problem. Thank you!

**Comment by jacobgil** [comment]
Closing for now, please re-open if there still is an issue.
