### ISSUE TITLE
Difference between Gradcam and just visualizing feature maps?

### ISSUE THREAD

**Issue by MaxPolak97** [jacobgil/pytorch-grad-cam#354]
As I understand now Gradcam allows us to give a better overview how the model has come to certain prediction while this isn't the case for visualizing feature maps. Can anyone tell whether this is correct?

**Comment by jacobgil** [comment]
Yes.
Lets say we're using a Resnet50 - we will have 2048 feature maps at the output of the CNN part.
Some of them could be relevant to a speicifc category, some could be irrelevant.

One issue with looking at all of them, is that it's not friendly for humans to understand, since it's so much data.
We could summarize them by clustering them with PCA/NMF.
This is the idea in EigenCAM / Deep Feature Factorization.

However methods like Grad-CAM let us select a subset of the feature map, that correspond with a specific category.
