### ISSUE TITLE
Does pytorch Grad-cam support image regression as well?

### ISSUE THREAD

**Issue by MaxPolak97** [jacobgil/pytorch-grad-cam#360]
In the tutorials, I saw that you could use Grad-cam for image classification tasks to visualize the important features that has led to the predictions of any present target class in ImageNet for a certain image. Could you use Grad-cam for image regression as well? For example, the model predicts someone age 58 years and I want to know where the model is looking at to decide someone is that age.

**Comment by jacobgil** [comment]
Yes.
You can just use the `BinaryClassifierOutputTarget` target from utils.model_targets.
[BinaryClassifierOutputTarget](https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/utils/model_targets.py#L26)

The name classifier can be removed from that class since it holds for regression as well.

The category it accepts will be 0 or 1.
If 1, it will show what pulls it towards higher ages.
If 0, it will show what pulls it towards lower ages.

I would start with this.
