### ISSUE TITLE
CAM with full negative values

### ISSUE THREAD

**Issue by yuchen2580** [jacobgil/pytorch-grad-cam#42]
Hi, I am trying to apply grad-cam on DL-based detectors.

The performance is not ideal. I notice after the operation on line 126-129:

```
        for i, w in enumerate(weights):
            cam += w * target[i, :, :]
        cam = np.maximum(cam, 0)
```

The most part of the cam are negative therefore assigned 0.
When doing a visualization, a region that has a detected objects might not show any response.

Is this because the regression on coordinates interrupt the results? 
Is there a way to get around this?

**Comment by lmz123321** [comment]
Hi @yuchen2580 , I have the same issue. Do you solve it?

**Comment by ShaheenPerveen** [comment]
@yuchen2580  and @lmz123321  were you guys able to figure out a way around this? I am also stuck in the same situation

**Comment by PWman** [comment]
I also have the same problem.  I have found this quote from the original paper that may be helpful in explaining why:

"
We apply a ReLU to the linear combination
of maps because we are only interested in the features that
have a positive influence on the class of interest, i.e. pixels
whose intensity should be increased in order to increase yc.
Negative pixels are likely to belong to other categories in the
image. As expected, without this ReLU, localization maps
sometimes highlight more than just the desired class and
perform worse at localization.
"

The line "np.maximum(cam,0)" is essentially applying that ReLU function described above. When the arrays are filled only with negative pixel values, I think it would mean that there have been no regions which have positively contributed to the classification, only regions which have decreased the probability of the output prediction. So my guess would be that the CNN is making its decision purely on which class looks the "least bad"; i.e. all regions of the input reduce the prediction probability of all possible classes, they just reduce it the least for the predicted class.

I am not an expert on DNNs but this is my two cents! Hope it helps.

**Comment by jacobgil** [comment]
Hi,
Are you doing the backward on the coordinate regression outputs, or on the category?
Can you share more details?

**Comment by hanikh** [comment]
Hi, 
@jacobgil thanks for your great work.
 I am trying to apply grad-cam on faster-rcnn (detectron2) and I am ding the backward on the category. I have the same problem and all the elements of the cam (before Relu) are negative.
would you please help me figure out what the probem is?
