### ISSUE TITLE
which conv layer I real need? 

### ISSUE THREAD

**Issue by wangdi19941224** [jacobgil/pytorch-grad-cam#43]
I use your code on my own CNN network(Inception-v3), and each conv layer's result is shown. However the last two conv layer's output thermal zone are totally diffiernet on one case, which thermal zone is the useful one?

**Comment by pshwetank** [comment]
Hi @wangdi19941224 , thats a very good question. Actually, we still dont have an answer to how to find the right layer for the visualisation yet. This is partly because the interpretation of these class activation visualisations are very subjective. The features you think are useful for the interpretation may slightly vary from one experimenter to another. The only way for you is to randomly look around the initial CNN layers, as well as, layers which are 1-2 conv blocks before the final conv layers. That can be your best shot at finding the correct layer for visualization. 
Now, regarding Inception V-3, its architecture is not feedforward like VGG-16 or LeNet. There are many varying filter size layers in between along with the skip connections. The skip connections are also the case for ResNet. That is why you will not get the expected beautiful visualizations you expect in ResNet and Inception. So, my advise will be to look out for the useful features in the layers I suggested in the first paragraph.

**Comment by pshwetank** [comment]
Bonus: I am also working on Grad-CAM implementation that can work on different custom architectures in Pytorch. Its still in development but you might get some ideas regarding the changes that you might have to make. 
https://github.com/pshwetank/grad-cam-pytorch

**Comment by wangdi19941224** [comment]
> Hi @wangdi19941224 , thats a very good question. Actually, we still dont have an answer to how to find the right layer for the visualisation yet. This is partly because the interpretation of these class activation visualisations are very subjective. The features you think are useful for the interpretation may slightly vary from one experimenter to another. The only way for you is to randomly look around the initial CNN layers, as well as, layers which are 1-2 conv blocks before the final conv layers. That can be your best shot at finding the correct layer for visualization.
> Now, regarding Inception V-3, its architecture is not feedforward like VGG-16 or LeNet. There are many varying filter size layers in between along with the skip connections. The skip connections are also the case for ResNet. That is why you will not get the expected beautiful visualizations you expect in ResNet and Inception. So, my advise will be to look out for the useful features in the layers I suggested in the first paragraph.

Thank you for your reply, In subsequent experiments, we found that the interpretability of the convolutional layer of the last layer is relatively reasonable in combination with the label information.This point is consistent with the point of view of the paper, but I personally think that for CNN, each convolutional layer has its role and interpretability.I hope that future work can clarify the value of different convolutional layers. Finally, thank you again for your reply. I will continue to pay attention to the progress of this work.
